version: "3.8"

services:
    ollama:
        image: ollama/ollama:0.32.5
        ports:
            - 11434:11434
        volumes:
            - ./ollama/data:/root/.ollama
        container_name: ollama
        tty: true
        restart: unless-stopped

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        restart: always
        environment:
          - 'OLLAMA_BASE_URL=http://ollama:11434'
          - 'WEBUI_SECRET_KEY='
        ports:
            - "3000:8080"
        volumes:
            - ./open-webui/data:/app/backend/data
